# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 20m
  tests: true
  skip-dirs-use-default: true
  skip-files:
    - bindings/gen_taiko_l1.go
    - bindings/gen_taiko_l2.go

issues:
  exclude-rules:
    - path: bindings/encoding/custom_error.go
      linters:
        - errorlint
    - path: pkg/tx_list_validator/tx_list_validator_test.go
      linters:
        - typecheck
    - path: prover/proof_submitter/merkle_proof_test.go
      linters:
        - typecheck

linters:
  disable-all: true
  enable:
    - bidichk
    - durationcheck
    - exportloopref
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3
    min-occurrences: 6
