definitions:
  server.ProposeBlockResponse:
    properties:
      prover:
        type: string
      signedPayload:
        items:
          type: integer
        type: array
    type: object
  server.Status:
    properties:
      currentCapacity:
        type: integer
      maxExpiry:
        type: integer
      minProofFee:
        type: integer
    type: object
host: prover-api.test.taiko.xyz
info:
  contact:
    email: info@taiko.xyz
    name: API Support
    url: https://community.taiko.xyz/
  license:
    name: MIT
    url: hhttps://github.com/taikoxyz/taiko-client/blob/main/LICENSE.md
  termsOfService: http://swagger.io/terms/
  title: Taiko Prover API
  version: "1.0"
paths:
  /assignment:
    post:
      consumes:
      - application/json
      operationId: create-assignment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.ProposeBlockResponse'
        "422":
          description: prover does not have capacity
          schema:
            type: string
      summary: Try to accept a block proof assignment
  /status:
    get:
      consumes:
      - application/json
      operationId: get-status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Status'
      summary: Get current prover server status
swagger: "2.0"
