name: Comment Hive Results

on:
  repository_dispatch:
    types: [write]
  workflow_dispatch:
  pull_request:

jobs:
  comment:
    name: Comment Hive Tests Results
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:
