name: Swagger

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    build:
        name: Swagger autogen docs
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: swag init
              run: ./scripts/swagger.sh
