name: Swagger

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    build:
        name: Swagger autogen docs
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                go-version: 1.21
                cache: true  

            - run: go install github.com/swaggo/swag/cmd/swag@latest

            - name: swag init
              run: ./scripts/swagger.sh
